### ISSUE TITLE
Gradle Build Error: Missing Library anjlab/android-inapp-billing

### ISSUE THREAD

**Issue by Intoxiona** [praveendath92/MDroid#77]
Hey praveen!!
When I try to make the gradle build I get the following error:
```
Error:A problem occurred configuring project ':app'.
> Could not find library.aar (com.anjlab.android.iab.v3:library:1.0.29).
  Searched in the following locations:
      https://jcenter.bintray.com/com/anjlab/android/iab/v3/library/1.0.29/library-1.0.29.aar
```

Please fix this.
Greetings,
Intox

**Comment by praveendath92** [comment]
There you go! A very recent update to the library [broke things][1].

[1]: https://github.com/anjlab/android-inapp-billing-v3/issues/135
