### ISSUE TITLE
does not show discussiones forum

### ISSUE THREAD

**Issue by adminmoodle** [praveendath92/MDroid#85]
praveendath92/MDroid

i use the app but does not show the forum discussions

I ran from android studio and i got the following in the logcat

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2

**Comment by pkpio** [comment]
@adminmoodle What's the version of the Moodle site you are using? Forum discussions are not available on older on versions of Moodle.

**Comment by adminmoodle** [comment]
im using version 2.9

**Comment by adminmoodle** [comment]
@praveendath92 im using version 2.9

**Comment by pkpio** [comment]
Could you please check if [this function ](https://github.com/praveendath92/MDroid/blob/master/app/src/main/java/in/co/praveenkumar/mdroid/moodlerest/MoodleRestOption.java#L23) is enabled on your Moodle Web services?

**Comment by adminmoodle** [comment]
@praveendath92 yes, this function is enable in my moodle,

**Comment by adminmoodle** [comment]
@praveendath92 you were right, i changed the function to mod_forum_get_forum_discussions, and now is run correctly

**Comment by pkpio** [comment]
@adminmoodle  Glad to know that it has been resolved :smile:

**Comment by adminmoodle** [comment]
thanks so much, kind regards :)
