### ISSUE TITLE
unfertounly Mdroid have stoped

### ISSUE THREAD

**Issue by farihulrouf** [praveendath92/MDroid#88]
Hei Anybody helpme please ..when i running at android device Sony i have get message unfertounly have stoped ?

**Comment by pkpio** [comment]
Can't help without a stack trace.

**Comment by farihulrouf** [comment]
he it's working done :+1:  and very userful but i have a problem if I use my web url in my experience . i m using moodle 2.7 .ni got errot like this
Fetching token
Fetching site info
 Welcome farihul rouf

Syncdata
Syncing courses null
Sync failed

**Comment by pkpio** [comment]
This happens if the user account doesn't have permissions for some webservice functions.

**Comment by farihulrouf** [comment]
do you have any tutorial for permissions. ??

**Comment by pkpio** [comment]
There's a link in the readme file that points to the [docs](https://github.com/praveendath92/MDroid#documentation)

**Comment by farihulrouf** [comment]
I've followed the instructions of your website but still appear message (Syncing courses null) .
i m using moodle_mobile_app
