### ISSUE TITLE
Course Return Null

### ISSUE THREAD

**Issue by farihulrouf** [praveendath92/MDroid#90]
Hei can you tell me whyt the  Courses return nul
`http://myurl_moodle/moodle//webservice/rest/server.php?wstoken=4f9fe18ae8c0bb2f11ed459686796876&wsfunction=moodle_enrol_get_users_courses&moodlewsrestformat=json&userid=2`
`[]`

**Comment by pkpio** [comment]
Please stop from opening duplicate issues. This is a permissions issue with Moodle Web services. You may contact Moodle forums or Stackoverflow for a fix.
